const Joi = require('joi');
const { createUserSchema, updateUserSchema, loginUserSchema } = require('./user.schema');

const createAdminSchema = createUserSchema.keys({
    admin_ID: Joi.string().length(6).optional(), // Optional if generated by backend
    role: Joi.string().valid('superadmin', 'manager', 'staff')
});

const loginAdminSchema = loginUserSchema; // Admin login is generic

const updateAdminSchema = updateUserSchema.keys({
    role: Joi.string().valid('superadmin', 'manager', 'staff')
}).min(1);


const adminSchema = {
    createAdminSchema,
    loginAdminSchema,
    updateAdminSchema
};

module.exports = adminSchema;
