const Joi = require('joi');

const createAdminSchema = Joi.object({
    admin_ID: Joi.string().length(6).optional(), // Optional if generated by backend
    username: Joi.string().alphanum().min(3).max(30).required(),
    first_name: Joi.string().required(),
    last_name: Joi.string().required(),
    email: Joi.string().email().required(),
    profile_url: Joi.string().uri().optional().allow(null, ''),
    password: Joi.string().min(6).required(),
    role: Joi.string().valid('superadmin', 'manager', 'staff').required()
});

const loginAdminSchema = Joi.object({
    username: Joi.string().required(),
    password: Joi.string().required()
});

const updateAdminSchema = Joi.object({
    username: Joi.string().alphanum().min(3).max(30),
    first_name: Joi.string(),
    last_name: Joi.string(),
    email: Joi.string().email(),
    profile_url: Joi.string().uri().optional().allow(null, ''),
    password: Joi.string().min(6),
    role: Joi.string().valid('superadmin', 'manager', 'staff')
}).min(1);


const adminSchema = {
    createAdminSchema,
    loginAdminSchema,
    updateAdminSchema
};

module.exports = adminSchema;
